#pragma once

//
// This file contains all IDs of game assets x
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_NATURE 30
#define ID_TEX_BLACK 40
#define ID_TEX_INTRO 50


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_GROUND 6
#define OBJECT_TYPE_MYSTERYBOX_COIN 7 //with coin
#define OBJECT_TYPE_BUSH 8
#define OBJECT_TYPE_TREE1 9
#define OBJECT_TYPE_TREE2 10
#define OBJECT_TYPE_TREE3 11
#define OBJECT_TYPE_TREE4 12
#define OBJECT_TYPE_CLOUD 13
#define OBJECT_TYPE_STAIR0 20
#define OBJECT_TYPE_STAIR1 21
#define OBJECT_TYPE_STAIR2 22
#define OBJECT_TYPE_STAIR3 23
#define OBJECT_TYPE_STAIR4 24
#define OBJECT_TYPE_STAIR5 25
#define OBJECT_TYPE_STAIR6 26
#define OBJECT_TYPE_STAIR7 27
#define OBJECT_TYPE_STAIR8 28
#define OBJECT_TYPE_STAIR9 29
#define OBJECT_TYPE_WOOD 30
#define OBJECT_TYPE_PIPEBELOW 31
#define OBJECT_TYPE_PIPEABOVE 32
#define OBJECT_TYPE_WARPPIPE 33
#define OBJECT_TYPE_PRIZE 34
#define OBJECT_TYPE_MYSTERYBOX_MUSHROOM 35 //with mushroom
#define OBJECT_TYPE_KOOPAS 36
#define OBJECT_TYPE_KOOPAS_2 37
#define OBJECT_TYPE_WINGGOOMBA 38
#define OBJECT_TYPE_WINGKOOPAS 39

#define OBJECT_TYPE_BLACKBACKGROUND 40
#define OBJECT_TYPE_PAKKUNFLOWER1 41
#define OBJECT_TYPE_PAKKUNFLOWER2 42
#define OBJECT_TYPE_PAKKUNFLOWER3 43


#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_TITLE 51
#define OBJECT_TYPE_CURTAIN 52

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_PLATFORM 50000
#define ID_SPRITE_PLATFORM_BEGIN (ID_SPRITE_PLATFORM+1000)
#define ID_SPRITE_PLATFORM_MIDDLE (ID_SPRITE_PLATFORM+2000)
#define ID_SPRITE_PLATFORM_END (ID_SPRITE_PLATFORM+3000)

#define ID_SPRITE_GROUND 60000
#define ID_SPRITE_GROUND_BEGIN (ID_SPRITE_GROUND+1000)
#define ID_SPRITE_GROUND_MIDDLE (ID_SPRITE_GROUND+2000)
#define ID_SPRITE_GROUND_END (ID_SPRITE_GROUND+3000)

#define ID_SPRITE_MYSTERYBOX 70000

#define ID_SPRITE_BUSH 80000

#define ID_SPRITE_TREE1 90000
#define ID_SPRITE_TREE2 100000
#define ID_SPRITE_TREE3 110000
#define ID_SPRITE_TREE4	120000



#define ID_SPRITE_CLOUD 130000

#define ID_SPRITE_STAIR0 200000
#define ID_SPRITE_STAIR1 210000
#define ID_SPRITE_STAIR2 220000
#define ID_SPRITE_STAIR3 230000
#define ID_SPRITE_STAIR4 240000
#define ID_SPRITE_STAIR5 250000
#define ID_SPRITE_STAIR6 260000
#define ID_SPRITE_STAIR7 270000
#define ID_SPRITE_STAIR8 280000
#define ID_SPRITE_STAIR9 290000

#define ID_SPRITE_WOOD 300000

#define ID_SPRITE_PIPEBELOW 310000
#define ID_SPRITE_PIPEABOVE 320000
#define ID_SPRITE_WARPPIPE 330000

#define ID_SPRITE_PRIZE 340000

#define ID_SPRITE_COINFROMBOX 350000

#define ID_SPRITE_MUSHROOM 360000

#define ID_SPRITE_KOOPAS 370000
#define ID_SPRITE_KOOPAS_WALK (ID_SPRITE_KOOPAS + 1000)
#define ID_SPRITE_KOOPAS_IDLE (ID_SPRITE_KOOPAS + 2000)
#define ID_SPRITE_KOOPAS_SPIN (ID_SPRITE_KOOPAS + 3000)

#define ID_SPRITE_WINGGOOMBA 380000

#define ID_SPRITE_WINGKOOPAS 390000

#define ID_SPRITE_BLACKBACKGROUND 400000

#define ID_SPRITE_PAKKUN1 410000
#define ID_SPRITE_PAKKUN1_TOPLEFT (ID_SPRITE_PAKKUN1 + 1000)
#define ID_SPRITE_PAKKUN1_BOTLEFT (ID_SPRITE_PAKKUN1 + 2000)
#define ID_SPRITE_PAKKUN1_TOPRIGHT (ID_SPRITE_PAKKUN1 + 3000)
#define ID_SPRITE_PAKKUN1_BOTRIGHT (ID_SPRITE_PAKKUN1 + 4000)

#define ID_SPRITE_PAKKUN2 420000

#define ID_SPRITE_PAKKUN3 430000
#define ID_SPRITE_PAKKUN3_TOPLEFT (ID_SPRITE_PAKKUN3 + 1000)
#define ID_SPRITE_PAKKUN3_BOTLEFT (ID_SPRITE_PAKKUN3 + 2000)
#define ID_SPRITE_PAKKUN3_TOPRIGHT (ID_SPRITE_PAKKUN3 + 3000)
#define ID_SPRITE_PAKKUN3_BOTRIGHT (ID_SPRITE_PAKKUN3 + 4000)

#define ID_SPRITE_FIREBALL 440000

#define ID_SPRITE_TITLE 500000
#define ID_SPRITE_CURTAIN 510000